### ISSUE TITLE
Failed to show Yield Farming List And Disappeared Pairs

### ISSUE THREAD

**Issue by harwinvoid** [harwinvoid/sushi#1]
### Basic Info

platform:  Chrome of  latest version and Metamask

address: 0x1e037d858131227F007f0b723cEc08c181f386BC

## User Report

some body in sushi chinese tg report a problem like  below
the problem has been last at least 24 hours, kind of troubled him.
**it only occured when user connet to his metamask wallet.**  
if used a empty  account, there is no problem
**same problem with same account on mobile metamask**

![image](https://user-images.githubusercontent.com/12931494/119003809-9d5e6280-b9c0-11eb-9ba4-8897fca18776.png)

## Analysis Process

1.  since he can open sushi.com, it means it's not a netwok problem
2. then  guide user to open the developer console of Chrome.
3. user shared a Screenshot like be below

![image](https://user-images.githubusercontent.com/12931494/119005552-20cc8380-b9c2-11eb-91dc-ea3d124148e3.png)

it seem a crash in JavaScript， may be there is bug when calc assets in user wallet。

## Tg ScreenShot

![image](https://user-images.githubusercontent.com/12931494/119010588-ce419600-b9c6-11eb-93a0-a5fc0586c388.png)

## One More Question

![image](https://user-images.githubusercontent.com/12931494/119011654-da7a2300-b9c7-11eb-9c12-0db5bcef7118.png)

In the yield List,  the KM/USDT/ETH disappered. 

![image](https://user-images.githubusercontent.com/12931494/119011105-4b6d0b00-b9c7-11eb-9041-cc7ff257a409.png)

in the console 

![image](https://user-images.githubusercontent.com/12931494/119011261-73f50500-b9c7-11eb-8cea-90c8088faa78.png)

there is 4 invalid pairs , and below contain a USDT asset, I guess the disappered one is in invalid list.

```js
address: "0x9DA0B987A14708023Fe0530272d7017C87F77840"
assetAddress: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
collateralAddress: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
masterContract: "0x2cBA6Ab6574646Badc84F0544d05059e57a5dc42"
```

_is there any relation with the disappeared pairs with the BigNumer error？_

relate link: https://github.com/ChainSafe/web3.js/issues/2077

**Comment by omakasebar** [comment]
The first error has not been able to reproduce, ask the user to try again. There doesn't seem to be any BigNumber errors in the interface. Can the user identify the exact url he or she is on and the exact steps the user took to encounter this error? Did they click on something, etc? Is the user using a custom RPC network?

Additionally the second error seems to be a user error. I can see kmWETH/USDT just fine when I search kmWETH-. Additionally if the user has some staked on this interface the user should see the balance at the top of the table. You can reproduce user balances by going to `http://app.sushi.com/yield/debug/0x1e037d858131227F007f0b723cEc08c181f386BC`
